"""Non-destructive quick image editing pipeline."""

from .models import (
    CanvasBackground,
    CanvasSettings,
    EditOutputFormat,
    EditResult,
    EditSettings,
    FilterPreset,
    HandDrawSettings,
    HandPoint,
    HandStroke,
    HandTool,
    MosaicSettings,
    MosaicStroke,
    MosaicTool,
    LineArtAmount,
    LineArtBackground,
    LineArtSettings,
    PaletteSettings,
    PlacementMode,
    RecolorBlendMode,
    StickerSettings,
    TextPosition,
    TextSettings,
    TransparencySettings,
)
from .renderer import render_edit, render_preview
from .service import EditService
from .line_art import apply_line_art
from .palette import (
    PaletteMapping,
    apply_palette_mapping,
    apply_palette_mapping_preserve_shading,
    apply_palette_mapping_smooth,
    extract_palette,
    mapping_for_palette,
    quantize_image,
    rgba_digest,
)
from .sticker import apply_sticker
from .hand_draw import compose_hand_draw, render_hand_overlay, scale_hand_draw
from .mosaic import compose_mosaic, render_mosaic_overlay, scale_mosaic

__all__ = [
    "CanvasBackground",
    "CanvasSettings",
    "EditOutputFormat",
    "EditResult",
    "EditService",
    "EditSettings",
    "FilterPreset",
    "HandDrawSettings",
    "HandPoint",
    "HandStroke",
    "HandTool",
    "MosaicSettings",
    "MosaicStroke",
    "MosaicTool",
    "LineArtAmount",
    "LineArtBackground",
    "LineArtSettings",
    "PaletteSettings",
    "PlacementMode",
    "RecolorBlendMode",
    "StickerSettings",
    "TextPosition",
    "TextSettings",
    "TransparencySettings",
    "render_edit",
    "render_preview",
    "apply_line_art",
    "PaletteMapping",
    "apply_palette_mapping",
    "apply_palette_mapping_preserve_shading",
    "apply_palette_mapping_smooth",
    "extract_palette",
    "mapping_for_palette",
    "rgba_digest",
    "quantize_image",
    "apply_sticker",
    "compose_hand_draw",
    "render_hand_overlay",
    "scale_hand_draw",
    "compose_mosaic",
    "render_mosaic_overlay",
    "scale_mosaic",
]
